# Generated by Django 3.1.2 on 2020-10-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('Python', 'Python程序设计'), ('C', 'C语言程序设计')], default='Python', max_length=32, verbose_name='科目')),
                ('title', models.TextField(verbose_name='题目')),
                ('optionA', models.CharField(max_length=50, verbose_name='A选项')),
                ('optionB', models.CharField(max_length=50, verbose_name='B选项')),
                ('optionC', models.CharField(max_length=50, verbose_name='C选项')),
                ('optionD', models.CharField(max_length=50, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=32, verbose_name='答案')),
                ('level', models.CharField(choices=[('2', 'general'), ('1', 'easy'), ('3', 'difficult')], default='1', max_length=32, verbose_name='等级')),
                ('score', models.IntegerField(default=1, verbose_name='分数')),
            ],
            options={
                'verbose_name': '单项选择题',
                'verbose_name_plural': '单项选择题',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=32, verbose_name='密码')),
                ('gender', models.CharField(choices=[('male', '女'), ('female', '男')], default='男', max_length=32, verbose_name='性别')),
                ('dept', models.CharField(choices=[('信息工程学院', '信息工程学院')], default='信息工程学院', max_length=32, verbose_name='学院')),
                ('major', models.CharField(choices=[('计算机网络技术', '计算机网络技术'), ('计算机应用技术', '计算机应用技术'), ('软件技术', '软件技术'), ('云计算技术与应用', '云计算技术与应用'), ('大数据技术与应用', '大数据技术与应用'), ('网络安全与管理', '网络安全与管理'), ('电子信息工程技术', '电子信息工程技术')], default='计算机网络技术', max_length=32, verbose_name='专业')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('telephone', models.CharField(max_length=32, verbose_name='电话')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='教工号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=32, verbose_name='密码')),
                ('gender', models.CharField(choices=[('male', '女'), ('female', '男')], default='男', max_length=32, verbose_name='性别')),
                ('dept', models.CharField(choices=[('信息工程学院', '信息工程学院')], default='信息工程学院', max_length=32, verbose_name='学院')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('telephone', models.CharField(max_length=32, verbose_name='电话')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python程序设计'), ('C', 'C语言程序设计')], default='python', max_length=20, verbose_name='科目')),
                ('major', models.CharField(choices=[('计算机网络技术', '计算机网络技术'), ('计算机应用技术', '计算机应用技术'), ('软件技术', '软件技术'), ('云计算技术与应用', '云计算技术与应用'), ('大数据技术与应用', '大数据技术与应用'), ('网络安全与管理', '网络安全与管理'), ('电子信息工程技术', '电子信息工程技术')], max_length=32, verbose_name='考卷适用专业')),
                ('examtime', models.DateTimeField()),
                ('pid', models.ManyToManyField(to='exam.Question')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.teacher')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python程序设计'), ('C', 'C语言程序设计')], default='python', max_length=32, verbose_name='科目')),
                ('grade', models.IntegerField()),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grade',
            },
        ),
    ]
