# Generated by Django 3.1.2 on 2020-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20201031_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='userid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('2', 'general'), ('1', 'easy')], default='1', max_length=32, verbose_name='等级'),
        ),
    ]
