# Generated by Django 3.1.2 on 2020-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20201031_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('信息工程学院', '信息工程学院')], default='信息工程学院', max_length=32, verbose_name='学院')),
                ('major', models.CharField(choices=[('计算机网络技术', '计算机网络技术'), ('计算机应用技术', '计算机应用技术'), ('软件技术', '软件技术'), ('云计算技术与应用', '云计算技术与应用'), ('大数据技术与应用', '大数据技术与应用'), ('网络安全与管理', '网络安全与管理'), ('电子信息工程技术', '电子信息工程技术')], default='计算机网络技术', max_length=32, verbose_name='专业')),
                ('Class', models.CharField(max_length=32, verbose_name='班级')),
                ('subject', models.CharField(choices=[('Python', 'Python程序设计'), ('C', 'C语言程序设计')], default='python', max_length=20, verbose_name='科目')),
                ('tid', models.ManyToManyField(to='exam.Teacher')),
            ],
        ),
    ]
