# Generated by Django 3.1.2 on 2020-11-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201101_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='pid',
            new_name='qid',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], default='1', max_length=32, verbose_name='等级'),
        ),
    ]
